### ISSUE TITLE
Quadtrees can be rectangles

### ISSUE THREAD

**Issue by Shiroy** [Shiroy/Ares#11]
Modify the code to allow quadtrees to be rectangles.

See https://github.com/Shiroy/Ares/pull/10/files#diff-1be8fd77ece954562e84a2fe57ec4998R20

**Comment by Amyantis** [comment]
We can already use rectangles instead of squares, just change the next line to :
`quadTree.setShape(0, 0, map.getMapSize().x, map.getMapSize().y);`
